### ISSUE TITLE
pymongo version in requirements

### ISSUE THREAD

**Issue by TomVeniat** [VincSP/Dash-Vision#1]
The application won't start with the pymongo version specified in the requirements.txt (3.5.1), raising the following error:

```
Traceback (most recent call last):
  File "app.py", line 61, in <module>
    options=onLoad_database_options()))
  File "app.py", line 37, in onLoad_database_options
    for database in get_database_name()]
  File "app.py", line 16, in get_database_name
    dbl = client.list_database_names()
  File "/local/veniat/anaconda3/envs/dashvision/lib/python3.6/site-packages/pymongo/database.py", line 1138, in __call__
    self.__name, self.__client.__class__.__name__))
TypeError: 'Database' object is not callable. If you meant to call the 'list_database_names' method on a 'MongoClient' object it is failing because no such method exists.
```
Works fine with version 3.7.2 of pymongo.

**Comment by VincSP** [comment]
requirements.txt has been updated.
Normally, pip install requirements.txt should work fine.
Thanks for the issue.
